---
- name: "create directory for exports: {{ kxlops_mysql_migrate_export_dir }}"
  file:
    path: '{{ kxlops_mysql_migrate_export_dir }}'
    state: directory


- import_tasks: '{{ kxlops_mysql_migrate_subtask }}/main.yml'